unique_ids:
  forms:
    index: G6BQQGZOMW4Q44ESSAZNP6NUCSY43BRC
    index.sportpage: '1722910449198865088711935.7183'
  modules: {}
  server_modules:
    ServerModule1: '1722558720248992487425224.8964'
  assets:
    standard-page.html: UKOOHDUTSKBQRDEQSIYSFC2WWRSP5UVV
    theme.css: EGI3JEVJTEGLGSTRAR4EXQHXSX36PD65
  scripts: {}
